# src/hv/config/credentials.yaml.example
# Example credentials file - copy to credentials.yaml and fill in your values
gitlab:
  token: "your-gitlab-token"

asana:
  token: "your-asana-token"

gcloud:
  project_id: "your-project"
  credentials_file: "$HOME/.config/gcloud/application_default_credentials.json"

slack:
  bot_token: "your-slack-bot-token"

zoom:
  daily:
    id: "your-meeting-id"
    password: "your-meeting-password"
